# Generated by Django 5.2.5 on 2025-09-04 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_wantedad_price_anuncio_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wantedad',
            options={'verbose_name': 'Anúncio de Procurado', 'verbose_name_plural': 'Anúncios de Procurados'},
        ),
        migrations.AddField(
            model_name='wantedad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='wantedad',
            name='reward',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Recompensa'),
        ),
        migrations.AddField(
            model_name='wantedad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='wantedad',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='wantedad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='wantedad',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='wantedad',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='wantedad',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='wantedad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='wantedad',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título do Anúncio'),
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wanted_ads/%Y/%m/%d/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.wantedad', verbose_name='Anúncio')),
            ],
            options={
                'verbose_name': 'Imagem do Anúncio',
                'verbose_name_plural': 'Imagens dos Anúncios',
            },
        ),
    ]
