# Generated by Django 5.2.5 on 2025-09-25 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_wantedad_options_wantedad_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='ads.wantedad', verbose_name='Anúncio')),
                ('participant_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_p1', to=settings.AUTH_USER_MODEL, verbose_name='Participante 1')),
                ('participant_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_p2', to=settings.AUTH_USER_MODEL, verbose_name='Participante 2')),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
                'ordering': ['-updated_at'],
                'unique_together': {('ad', 'participant_1', 'participant_2')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ads.chatroom', verbose_name='Sala de Chat')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
    ]
